修复actions

diff --git a/.github/workflows/run.yaml b/.github/workflows/run.yaml
--- a/.github/workflows/run.yaml
+++ b/.github/workflows/run.yaml
@@ -16,12 +16,20 @@ jobs:
         name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
       -
-        name: Extract CLASH_VERSION from Dockerfile
+        name: Extract CLASH_VERSION
         id: extract_version
         run: |
           # 使用 grep 和 awk 提取 ARG CLASH_VERSION 的值
-          CLASH_VERSION=$(grep "ARG CLASH_VERSION=" Dockerfile | awk -F "=" '{print $2}' | tr -d '"' | tr -d ' \\\r\\n')
-          echo "CLASH_VERSION=${CLASH_VERSION}" >> $GITHUB_ENV
+          CLASH_VERSION=$(grep "ARG CLASH_VERSION=" Dockerfile | awk -F "=" '{print $2}' | tr -d '"' | tr -d ' \\t\\r\\n')
+          # 检查 CLASH_VERSION 是否为空
+          if [ -z "$CLASH_VERSION" ]; then
+            echo "ERROR: CLASH_VERSION is empty."
+            exit 1
+          fi
+          echo "clash_version=$CLASH_VERSION"
+        # 将提取的版本号作为输出
+        outputs:
+          clash_version: ${{ steps.extract_version.outputs.clash_version }}
       -
         name: Login to Docker Hub
         uses: docker/login-action@v3
@@ -33,5 +41,5 @@ jobs:
         uses: docker/build-push-action@v5
         with:
           push: true
-          # 使用环境变量作为镜像的标签，并添加 latest 标签
-          tags: 9527tech/clash:${CLASH_VERSION},9527tech/clash:latest
+          # 使用从上一个步骤传递的版本号作为镜像的标签，并添加 latest 标签
+          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clash:${{ steps.extract_version.outputs.clash_version }},${{ secrets.DOCKERHUB_USERNAME }}/clash:latest
